package iguanaman.hungeroverhaul.core;

/*
 * TConstructLoaderContainer is derived from code graciously provided by AlgorithmX2 of Applied Energistics.
 * The code was adapted for this loader by Sunstrike. Any queries should be directed to him, not AlgorithmX2.
 */

import java.util.Arrays;
import java.util.Map;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.google.common.eventbus.EventBus;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin;

public class HOLoaderContainer extends DummyModContainer implements IFMLLoadingPlugin
{

    private final String[] asmTransformers = new String[]{};
    private final ModMetadata md = new ModMetadata();

    public static Logger logger = LogManager.getLogger("HO-Core");

    public HOLoaderContainer()
    {
        logger.info("Constructing preloader (Modules: " + Arrays.toString(asmTransformers) + ")");

        md.autogenerated = false;
        md.modId = getModId();
        md.version = getVersion();
        md.name = getName();
        md.authorList = Arrays.asList("progwml6", "Parker8283");
        //md.description = "The mod responsible for allowing re-assignment of food values in MC 1.7+";
    }

    @Override
    public String getModId()
    {
        return "HO-Core";
    }

    @Override
    public String getName()
    {
        return "Hunger Overhaul Core";
    }

    @Override
    public String getVersion()
    {
        return "0.1.1";
    }

    @Override
    public String getDisplayVersion()
    {
        return getVersion();
    }

    @Override
    public ModMetadata getMetadata()
    {
        return md;
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller)
    {
        bus.register(this);
        return true;
    }

    @Override
    public String[] getASMTransformerClass()
    {
        return asmTransformers;
    }

    @Override
    public String getModContainerClass()
    {
        return "iguanaman.hungeroverhaul.core.HOLoaderContainer";
    }

    @Override
    public String getSetupClass()
    {
        return null;
    }

    @Override
    public void injectData(Map<String, Object> data)
    {
    }

    @Override
    public String getAccessTransformerClass()
    {
        return "iguanaman.hungeroverhaul.core.AccessTransformers";
    }
}
