package iguanaman.hungeroverhaul.module;

import iguanaman.hungeroverhaul.IguanaConfig;
import iguanaman.hungeroverhaul.api.FoodValues;
import iguanaman.hungeroverhaul.helper.FoodValueHelper;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;

import com.pam.harvestcraft.BlockRegistry;
import com.pam.harvestcraft.ItemRegistry;

import cpw.mods.fml.common.Loader;

public class ModuleHarvestCraft
{
    public static void init()
    {
        // SETUP VALUES
        float foodSaturation = 0.1F;
        if (IguanaConfig.modifyFoodValues)
        {
            ItemRegistry.cropfoodRestore = 1;
        }

        FoodValueHelper.addModifiedFoodValues(ItemRegistry.asparagusItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.barleyItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.beanItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.beetItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.broccoliItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.cauliflowerItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.celeryItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.cranberryItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.garlicItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.gingerItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.leekItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.lettuceItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.oatsItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.onionItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.parsnipItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.peanutItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.pineappleItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.radishItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.riceItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.rutabagaItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.ryeItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.scallionItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.soybeanItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.spiceleafItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.sunflowerseedsItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.sweetpotatoItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.tealeafItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.turnipItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.whitemushroomItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.artichokeItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.bellpepperItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.blackberryItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.blueberryItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.brusselsproutItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.cabbageItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.cactusfruitItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.candleberryItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.cantaloupeItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.chilipepperItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.coffeebeanItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.cornItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.cucumberItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.eggplantItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.grapeItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.kiwiItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.mustardseedsItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.okraItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.peasItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.raspberryItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.rhubarbItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.seaweedItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.strawberryItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.tomatoItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.wintersquashItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        FoodValueHelper.addModifiedFoodValues(ItemRegistry.zucchiniItem, new FoodValues(ItemRegistry.cropfoodRestore, foodSaturation));
        // HavestCraft Base
        if (IguanaConfig.modifyFoodValues)
        {
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.toastItem, new FoodValues(4, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cheeseItem, new FoodValues(1, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.icecreamItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.grilledcheeseItem, new FoodValues(7, 0.5F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.applejuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.applesauceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.applepieItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.caramelappleItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pumpkinbreadItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.roastedpumpkinseedsItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pumpkinsoupItem, new FoodValues(4, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.melonjuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.melonsmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.carrotjuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.carrotcakeItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.carrotsoupItem, new FoodValues(4, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.glazedcarrotsItem, new FoodValues(3, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.butteredpotatoItem, new FoodValues(4, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.loadedbakedpotatoItem, new FoodValues(8, 0.6F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.mashedpotatoesItem, new FoodValues(5, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.potatosaladItem, new FoodValues(4, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.potatosoupItem, new FoodValues(4, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.friesItem, new FoodValues(3, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.grilledmushroomItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.stuffedmushroomItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chickensandwichItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chickennoodlesoupItem, new FoodValues(7, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chickenpotpieItem, new FoodValues(8, 0.5F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.breadedporkchopItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.hotdogItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.bakedhamItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.hamburgerItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cheeseburgerItem, new FoodValues(8, 0.5F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.baconcheeseburgerItem, new FoodValues(9, 0.6F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.potroastItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.fishsandwichItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.fishsticksItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.fishandchipsItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.friedeggItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.scrambledeggItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.boiledeggItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.eggsaladItem, new FoodValues(3, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.caramelItem, new FoodValues(1, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.taffyItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.spidereyesoupItem, new FoodValues(3, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.zombiejerkyItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chocolatebarItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.hotchocolateItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chocolateicecreamItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.vegetablesoupItem, new FoodValues(6, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.stockItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.fruitsaladItem, new FoodValues(3, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.spagettiItem, new FoodValues(7, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.spagettiandmeatballsItem, new FoodValues(10, 0.5F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.tomatosoupItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chickenparmasanItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pizzaItem, new FoodValues(8, 0.5F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.springsaladItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.porklettucewrapItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.fishlettucewrapItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.bltItem, new FoodValues(9, 0.5F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.leafychickensandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.leafyfishsandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.deluxecheeseburgerItem, new FoodValues(10, 0.6F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.delightedmealItem, new FoodValues(16, 0.8F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.onionsoupItem, new FoodValues(4, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.potatocakesItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.hashItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.braisedonionsItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.heartybreakfastItem, new FoodValues(15, 0.8F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cornonthecobItem, new FoodValues(3, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cornbreadItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.tortillaItem, new FoodValues(3, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.nachoesItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.tacoItem, new FoodValues(8, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.fishtacoItem, new FoodValues(8, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.creamedcornItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.strawberrysmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.strawberrypieItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.strawberrysaladItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.strawberryjuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chocolatestrawberryItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.peanutbutterItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.trailmixItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pbandjItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.peanutbuttercookiesItem, new FoodValues(3, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.grapejuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.grapejellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.grapesaladItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.raisincookiesItem, new FoodValues(3, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.picklesItem, new FoodValues(3, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cucumbersaladItem, new FoodValues(5, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cucumbersoupItem, new FoodValues(4, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.vegetarianlettucewrapItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.marinatedcucumbersItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.ricesoupItem, new FoodValues(5, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.friedriceItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.mushroomrisottoItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.curryItem, new FoodValues(10, 0.55F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.rainbowcurryItem, new FoodValues(13, 0.7F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.refriedbeansItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.bakedbeansItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.beansandriceItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chiliItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.beanburritoItem, new FoodValues(8, 0.5F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.stuffedpepperItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.veggiestirfryItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.grilledskewersItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.supremepizzaItem, new FoodValues(12, 0.7F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.omeletItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.hotwingsItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chilipoppersItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.extremechiliItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chilichocolateItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.lemonaideItem, new FoodValues(1, 0.0F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.lemonbarItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.fishdinnerItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.lemonsmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.lemonmeringueItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.candiedlemonItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.lemonchickenItem, new FoodValues(7, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blueberrysmoothieItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blueberrypieItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blueberrymuffinItem, new FoodValues(4, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blueberryjuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pancakesItem, new FoodValues(4, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blueberrypancakesItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cherryjuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cherrypieItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chocolatecherryItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cherrysmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cheesecakeItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cherrycheesecakeItem, new FoodValues(7, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.stuffedeggplantItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.eggplantparmItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.raspberryicedteaItem, new FoodValues(1, 0.0F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chaiteaItem, new FoodValues(0, 0.0F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.espressoItem, new FoodValues(1, 0.0F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.coffeeconlecheItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.mochaicecreamItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pickledbeetsItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.beetsaladItem, new FoodValues(4, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.beetsoupItem, new FoodValues(4, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.bakedbeetsItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.broccolimacItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.broccolindipItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.creamedbroccolisoupItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.sweetpotatopieItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.candiedsweetpotatoesItem, new FoodValues(3, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.mashedsweetpotatoesItem, new FoodValues(3, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.steamedpeasItem, new FoodValues(3, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.splitpeasoupItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pineappleupsidedowncakeItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pineapplehamItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pineappleyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.turnipsoupItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.roastedrootveggiemedleyItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.bakedturnipsItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.gingerbreadItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.gingersnapsItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.candiedgingerItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.softpretzelandmustardItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.spicymustardporkItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.spicygreensItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.garlicbreadItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.garlicmashedpotatoesItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.garlicchickenItem, new FoodValues(7, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.summerradishsaladItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.summersquashwithradishItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.celeryandpeanutbutterItem, new FoodValues(3, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chickencelerycasseroleItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.peasandceleryItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.celerysoupItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.zucchinibreadItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.zucchinifriesItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.zestyzucchiniItem, new FoodValues(9, 0.5F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.zucchinibakeItem, new FoodValues(9, 0.5F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.asparagusquicheItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.asparagussoupItem, new FoodValues(4, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.walnutraisinbreadItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.candiedwalnutsItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.brownieItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.papayajuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.papayasmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.papayayogurtItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.starfruitjuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.starfruitsmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.starfruityogurtItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.guacamoleItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.creamofavocadosoupItem, new FoodValues(6, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.avocadoburritoItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.poachedpearItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.fruitcrumbleItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pearyogurtItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.plumyogurtItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.bananasplitItem, new FoodValues(7, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.banananutbreadItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.bananasmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.bananayogurtItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.coconutmilkItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chickencurryItem, new FoodValues(9, 0.5F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.coconutshrimpItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.coconutyogurtItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.orangejuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.orangechickenItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.orangesmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.orangeyogurtItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.peachjuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.peachcobblerItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.peachsmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.peachyogurtItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.limejuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.keylimepieItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.limesmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.limeyogurtItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.mangojuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.mangosmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.mangoyogurtItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pomegranatejuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pomegranatesmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pomegranateyogurtItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.vanillayogurtItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cinnamonrollItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.frenchtoastItem, new FoodValues(7, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.marshmellowsItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.donutItem, new FoodValues(4, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chocolatedonutItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.powdereddonutItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.jellydonutItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.frosteddonutItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cactussoupItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.wafflesItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.seedsoupItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.softpretzelItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.jellybeansItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.biscuitItem, new FoodValues(4, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.creamcookieItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.jaffaItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.friedchickenItem, new FoodValues(7, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chocolatesprinklecakeItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.redvelvetcakeItem, new FoodValues(7, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.footlongItem, new FoodValues(9, 0.55F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blueberryyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.lemonyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cherryyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.strawberryyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.grapeyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chocolateyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blackberryjuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blackberrycobblerItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blackberrysmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blackberryyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chocolatemilkItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pumpkinyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.raspberryjuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.raspberrypieItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.raspberrysmoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.raspberryyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cinnamonsugardonutItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.melonyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.kiwijuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.kiwismoothieItem, new FoodValues(3, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.kiwiyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.plainyogurtItem, new FoodValues(1, 0.0F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.appleyogurtItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.saltedsunflowerseedsItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.sunflowerwheatrollsItem, new FoodValues(6, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.sunflowerbroccolisaladItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cranberryjuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cranberrysauceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cranberrybarItem, new FoodValues(5, 0.3F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.peppermintItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cactusfruitjuiceItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.baklavaItem, new FoodValues(7, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.gummybearsItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.baconmushroomburgerItem, new FoodValues(10, 0.65F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.fruitpunchItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.meatystewItem, new FoodValues(6, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.mixedsaladItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pinacoladaItem, new FoodValues(2, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.shepardspieItem, new FoodValues(6, 0.4F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.eggnogItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.custardItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.sushiItem, new FoodValues(3, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.gardensoupItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.muttonrawItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.muttoncookedItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.calamarirawItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.calamaricookedItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.applejellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.applejellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blackberryjellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blackberryjellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blueberryjellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blueberryjellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cherryjellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cherryjellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cranberryjellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cranberryjellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.kiwijellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.kiwijellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.lemonjellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.lemonjellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.limejellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.limejellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.mangojellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.mangojellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.orangejellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.orangejellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.papayajellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.papayajellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.peachjellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.peachjellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pomegranatejellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pomegranatejellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.raspberryjellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.raspberryjellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.starfruitjellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.starfruitjellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.strawberryjellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.strawberryjellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.watermelonjellyItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.watermelonjellysandwichItem, new FoodValues(8, 0.45F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cherrysodaItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.colasodaItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.gingersodaItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.grapesodaItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.lemonlimesodaItem, new FoodValues(3, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.orangesodaItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.rootbeersodaItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.strawberrysodaItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.caramelicecreamItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.mintchocolatechipicemcreamItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.strawberryicecreamItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.vanillaicecreamItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.ediblerootItem, new FoodValues(1, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.gingerchickenItem, new FoodValues(6, 0.35F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.oldworldveggiesoupItem, new FoodValues(4, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.spicebunItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.gingeredrhubarbtartItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.lambbarleysoupItem, new FoodValues(5, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.honeylemonlambItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pumpkinoatsconesItem, new FoodValues(3, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.beefjerkyItem, new FoodValues(3, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.plumjuiceItem, new FoodValues(2, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pearjuiceItem, new FoodValues(2, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.ovenroastedcauliflowerItem, new FoodValues(5, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.leekbaconsoupItem, new FoodValues(4, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.herbbutterparsnipsItem, new FoodValues(4, 0.2F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.scallionbakedpotatoItem, new FoodValues(4, 0.25F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.soymilkItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.firmtofuItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.silkentofuItem, new FoodValues(3, 0.15F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.grilledasparagusItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.avocadoItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.bananaItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.bellpepperItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blackberryItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.blueberryItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cactusfruitItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cantaloupeItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cherryItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.chilipepperItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.coconutItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.toastedcoconutItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.coffeeItem, new FoodValues(0, 0.0F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cornItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.popcornItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cranberryItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.cucumberItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.dragonfruitItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.eggplantItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.grilledeggplantItem, new FoodValues(2, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.grapeItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.raisinsItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.kiwiItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.lemonItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.limeItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.lettuceItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.mangoItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.nutmegItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.oliveItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.orangeItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.papayaItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.peachItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pearItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.plumItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.pomegranateItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.raspberryItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.riceItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.ricecakeItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.spiceleafItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.starfruitItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.strawberryItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.tealeafItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.teaItem, new FoodValues(2, 0.1F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.tomatoItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.walnutItem, new FoodValues(1, 0.05F));
            FoodValueHelper.addModifiedFoodValues(ItemRegistry.zucchiniItem, new FoodValues(1, 0.05F));
        }

        // SAPLING ASPECTS
        if (Loader.isModLoaded("Thaumcraft"))
        {
            AspectList saplingAspects = new AspectList().add(Aspect.PLANT, 1).add(Aspect.TREE, 1);
            Block saplings[] = new Block[]{
            BlockRegistry.pamappleSapling, BlockRegistry.pamavocadoSapling, BlockRegistry.pambananaSapling,
            BlockRegistry.pamcherrySapling, BlockRegistry.pamcinnamonSapling, BlockRegistry.pamcoconutSapling,
            BlockRegistry.pamdragonfruitSapling, BlockRegistry.pamlemonSapling, BlockRegistry.pamlimeSapling,
            BlockRegistry.pammangoSapling, BlockRegistry.pamnutmegSapling, BlockRegistry.pamoliveSapling,
            BlockRegistry.pampapayaSapling, BlockRegistry.pampearSapling, BlockRegistry.pampeppercornSapling,
            BlockRegistry.pamplumSapling, BlockRegistry.pampomegranateSapling, BlockRegistry.pamstarfruitSapling,
            BlockRegistry.pamvanillabeanSapling, BlockRegistry.pamwalnutSapling
            };
            for (Block sapling : saplings)
                registerAspects(Item.getItemFromBlock(sapling), saplingAspects);
        }
    }

    public static void registerAspects(Item item, AspectList aspects)
    {
        if (!ThaumcraftApi.exists(item, -1))
            ThaumcraftApi.registerObjectTag(new ItemStack(item, 1), new int[]{-1}, aspects);
    }
}
